version: '3.8'

services:
  docker-emailserver-landing:
    build: .
    container_name: docker-emailserver-landing
    ports:
      - "3034:80"
    restart: unless-stopped
    environment:
      - TZ=Europe/Kyiv
